/**
 * Renders the corpus into one snapshot per source file.
 *
 * The grouping mirrors the block sources, so converting a single file during the TypeScript
 * migration can only ever change that file's snapshot - which keeps the review of each step small.
 */
const { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } = require('node:fs');
const { join } = require('node:path');
const { createBlocklyEnvironment } = require('./env');
const { buildCorpus } = require('./corpus');

const GOLDEN_DIR = join(__dirname, 'golden');
const HEADER = '// Generated by "npm run test:blockly:update". Do not edit by hand.';

/**
 * Blocks whose definition *and* generator come from the npm plugins that `initBlockly()` installs
 * (`src-editor/src/Components/blockly-plugins`). They are already TypeScript and therefore not part
 * of the JS -> TS migration, so this harness deliberately does not load them. Listed instead of
 * silently dropped, so the gap stays visible.
 */
const PLUGIN_BLOCKS = new Set(['comment', 'colour_blend', 'colour_picker', 'colour_random', 'colour_rgb', 'text_multiline']);

/**
 * Generates code for every corpus entry and groups the result.
 *
 * @param {ReturnType<typeof createBlocklyEnvironment>} [env] Reuse an environment; a fresh one is
 *   created when omitted. Passing the same environment twice must produce the same result - that is
 *   what the determinism check in the test relies on.
 * @returns {{ snapshots: Record<string, string>, blockCount: number, failures: string[] }}
 */
function buildSnapshots(env = createBlocklyEnvironment()) {
    const corpus = buildCorpus(env);
    const grouped = {};
    const failures = [];

    for (const entry of corpus) {
        let body;
        if (entry.group === 'fixtures') {
            // whole workspaces - always generated, never "just a block type"
            try {
                const { code, warnings } = env.generate(entry.xml);
                body = code.trimEnd() || '(no code)';
                if (warnings.length) {
                    body += `\n${warnings.map(w => `// WARNING: ${w}`).join('\n')}`;
                }
            } catch (e) {
                body = `// ERROR: ${e.message}`;
                failures.push(`${entry.type}: ${e.message}`);
            }
        } else if (PLUGIN_BLOCKS.has(entry.type)) {
            body = '(provided by blockly-plugins/initBlockly - not covered by this harness)';
        } else if (!env.Blockly.JavaScript.forBlock[entry.type]) {
            // Mutator containers and their items only ever live inside a mutator's mini workspace
            // and have no generator by design. Keeping them listed means a block that disappears
            // still shows up as a diff.
            body = '(no generator - mutator or UI-only block)';
        } else {
            try {
                const { code, warnings } = env.generate(entry.xml);
                body = code.trimEnd() || '(no code)';
                if (warnings.length) {
                    // Warnings belong in the snapshot: a field that silently loses its value changes
                    // the generated code, and we want that to show up as a diff, not to pass quietly.
                    body += `\n${warnings.map(w => `// WARNING: ${w}`).join('\n')}`;
                }
            } catch (e) {
                body = `// ERROR: ${e.message}`;
                failures.push(`${entry.type}: ${e.message}`);
            }
        }

        grouped[entry.group] = grouped[entry.group] || [];
        grouped[entry.group].push(`===== ${entry.type} [${entry.source}] =====\n${body}`);
    }

    const snapshots = {};
    for (const group of Object.keys(grouped).sort()) {
        snapshots[group] =
            `${HEADER}\n// ${grouped[group].length} block(s) from "${group}"\n\n${grouped[group].join('\n\n')}\n`;
    }

    return { snapshots, blockCount: corpus.length, failures };
}

/** Writes the snapshots to test/blockly/golden/ and returns the file names */
function writeSnapshots(snapshots) {
    if (!existsSync(GOLDEN_DIR)) {
        mkdirSync(GOLDEN_DIR, { recursive: true });
    }
    const written = [];
    for (const group of Object.keys(snapshots)) {
        writeFileSync(join(GOLDEN_DIR, `${group}.txt`), snapshots[group]);
        written.push(`${group}.txt`);
    }
    return written;
}

/** Reads the committed snapshots */
function readSnapshots() {
    if (!existsSync(GOLDEN_DIR)) {
        return {};
    }
    const stored = {};
    for (const file of readdirSync(GOLDEN_DIR).filter(f => f.endsWith('.txt'))) {
        stored[file.replace(/\.txt$/, '')] = readFileSync(join(GOLDEN_DIR, file), 'utf8');
    }
    return stored;
}

module.exports = { buildSnapshots, writeSnapshots, readSnapshots, GOLDEN_DIR };
