/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "name":                 {"en": "name",                  "de": "Name",                   "ru": "Имя"},
    "engine type":          {"en": "engine type",           "de": "Enginetyp",              "ru": "Тип движка"},
    "Insert ID":            {"en": "Insert ID",             "de": "ID Einfügen",            "ru": "Вставить ID"},
    "Ok":                   {"en": "Ok",                    "de": "Ok",                     "ru": "Ok"},
    "Cron":                 {"en": "Cron",                  "de": "Cron",                   "ru": "Cron"},
    "Cron expression":      {"en": "Cron expression",       "de": "Cron-Ausdruck",          "ru": "Cron-Выражение"},
    "Cancel":               {"en": "Cancel",                "de": "Abbrechen",              "ru": "Отмена"},
    "enabled":              {"en": "enabled",               "de": "Aktiviert",              "ru": "активно"},
    "engine":               {"en": "engine",                "de": "Ausführen mit",          "ru": "Движок"},
    "true":                 {"en": "true",                  "de": "ja",                     "ru": "да"},
    "false":                {"en": "false",                 "de": "nein",                   "ru": "нет"},
    "Insert":               {"en": "Insert",                "de": "Einfügen",               "ru": "Вставить"},
    "Minutes Past the Hour": {"en": "Minutes Past the Hour", "de": "Minuten nach volle Stunde", "ru": "минут после полного часа"},
    "Time: Hour":           {"en": "Time: Hour",            "de": "Zeit: Stunde",           "ru": "Время: Час"},
    "Day of Month":         {"en": "Day of Month",          "de": "Monatstag",              "ru": "День месяца"},
    "Time: Minute":         {"en": "Time: Minute",          "de": "Zeit: Minute",           "ru": "Время: Минуты"},
    "copy":                 {"en": "copy",                  "de": "kopieren",               "ru": "копировать"},
    "Every":                {"en": "Every",                 "de": "Jede(n)",                "ru": "Каждую(ый)"},
    "on the":               {"en": "on the",                "de": "am",                     "ru": " "},
    "on":                   {"en": "on",                    "de": "am",                     "ru": " "},
    "at":                   {"en": "at",                    "de": "um",                     "ru": "в"},
    "of":                   {"en": "of",                    "de": "",                       "ru": " "},
    "Scripts": {
        "en": "Scripts",
        "de": "Skripte",
        "ru": "Скрипты"
    },
    "delete script":        {"en": "delete script",         "de": "Script löschen",         "ru": "Удалить скрипт"},
    "edit script":          {"en": "edit script",           "de": "Script bearbeiten",      "ru": "Редактироветь скрипт"},
    "new script":           {"en": "new script",            "de": "Neues Script",           "ru": "Новый скрипт"},
    "edit file":            {"en": "edit file",             "de": "Datei editieren",        "ru": "Редактировать"},
    "restart script":       {"en": "restart script",        "de": "Skript neu starten",     "ru": "Перезапустить скрипт"},
    "Save":                 {"en": "Save",                  "de": "Speichern",              "ru": "Сохранить"},
    "edit":                 {"en": "edit",                  "de": "ändern",                 "ru": "редактировать"},
    "delete":               {"en": "delete",                "de": "löschen",                "ru": "удалить"},
    "ok":                   {"en": "Ok",                    "de": "Ok",                     "ru": "Ok"},
    "cancel":               {"en": "Cancel",                "de": "Abbrechen",              "ru": "отменить"},
    "global":               {"en": "global",                "de": "Global",                 "ru": "глобальный"},
    "months":               {
        "en": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "de": ["Januar", "Februar", "März", "April", "Mai", "Juni", "July", "August", "September", "Oktober", "November", "Dezember"],
        "ru": ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"]
    },
    "daysofweek":           {
        "en": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        "de": ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"],
        "ru": ["Воскресение", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"]
    },
    "periods":              {
        "en": ["minute", "hour", "day", "week", "month", "year"],
        "de": ["Minute", "Stunde", "Tag", "Woche", "Monat", "Jahr"],
        "ru": ["минуту", "час", "день", "неделю", "месяц", "год"]
    },
    "daysofmonth":          {
        "en": [  '0th',  '1st',  '2nd',  '3rd',  '4th',  '5th',  '6th',  '7th',  '8th',  '9th',
                '10th', '11th', '12th', '13th', '14th', '15th', '16th', '17th', '18th', '19th',
                '20th', '21st', '22nd', '23rd', '24th', '25th', '26ht', '27th', '28ht', '29ht',
                '30th', '31st'],
        "de": [  '0en',  '1en',  '2en',  '3en',  '4en',  '5en',  '6en',  '7en',  '8en',  '9en',
                '10en', '11en', '12en', '13en', '14en', '15en', '16en', '17en', '18en', '19en',
                '20en', '21en', '22en', '23en', '24en', '25en', '26en', '27en', '28en', '29en',
                '30en', '31en'],
        "ru": [  '0',   '1го',   '2го',  '3го',  '4го',  '5го',  '6го',  '7го',  '8го',  '9го',
                '10го', '11го', '12го', '13го', '14го', '15го', '16го', '17го', '18го', '19го',
                '20го', '21го', '22го', '23го', '24го', '25го', '26го', '27го', '28го', '29го',
                '30го', '31го'],
    },
    "Name":                 {"en": "Name",                  "de": "Name",                   "ru": "Имя"},
    "Select ID":            {"en": "Select ID",             "de": "ID Auswählen",           "ru": "Выбрать ID"},
    "Select":               {"en": "Select",                "de": "Auswählen",              "ru": "Выбрать"},
    "All":                  {"en": "All",                   "de": "Alle",                   "ru": "все"},
    "ID":                   {"en": "ID",                    "de": "ID",                     "ru": "ID"},
    "Role":                 {"en": "Role",                  "de": "Rolle",                  "ru": "Роль"},
    "Room":                 {"en": "Room",                  "de": "Raum",                   "ru": "Комната"},
    "Value":                {"en": "Value",                 "de": "Wert",                   "ru": "Значение"},
    "From":                 {"en": "From: ",                "de": "Von",                    "ru": "От"},
    "Last changed":         {"en": "Last changed",          "de": "Lätze Änderung",         "ru": "Изменён"},
    "Time stamp":           {"en": "Time stamp",            "de": "Zeitstempel",            "ru": "Время"},
    "Acknowledged":         {"en": "Acknowledged",          "de": "Bestätigt",              "ru": "Подтверждён"},
    "Processing...":        {"en": "Processing...",         "de": "Bearbeite...",           "ru": "Обработка..."}
};
