var MSG = {
    title: "Code",
    blocks: "Bloki",
    linkTooltip: "Zapisz i połącz z blokami.",
    runTooltip: "Uruchom program zdefiniowany przez bloki w obszarze roboczym.",
    badCode: "Błąd programu:\n%1",
    timeout: "Przekroczono maksymalną liczbę iteracji wykonania.",
    trashTooltip: "Odrzuć wszystkie bloki.",
    catLogic: "Logika",
    catLoops: "Pętle",
    catMath: "Matematyka",
    catText: "Tekst",
    catLists: "Listy",
    catColour: "Kolor",
    catVariables: "Zmienne",
    catFunctions: "Funkcje",
    listVariable: "lista",
    textVariable: "tekst",
    httpRequestError: "Wystąpił problem z żądaniem.",
    linkAlert: "Udostępnij swoje bloki za pomocą tego linku:\n\n%1",
    hashError: "Przepraszamy, '%1' nie odpowiada żadnemu zapisanemu programowi.",
    xmlError: "Nie można załadować zapisanego pliku. Być może został utworzony za pomocą innej wersji Blockly?",
    badXml: "Błąd podczas analizowania pliku XML:\n%1\n\nWybierz 'OK', aby zrezygnować ze zmian, lub 'Anuluj', aby dalej edytować plik XML."
};
