name: Auto approve

on:
  pull_request:
    types: [labeled]

jobs:
  auto-approve:
    if: |
      github.actor == 'foxbot76' &&
      github.event.label.name == 'automated pr 🔧'

    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}